apiVersion: skyline.adobe.com/v1alpha1
kind: SkylineFastlyService
metadata:
  annotations:
    cdn-operator.skyline.adobe.com/cdnconfig-hash: ba3d3eaeb47fe0b5afcdf499edcb9174638aa3d9
    cm.adobe.com/correlationId: QJS3QJyyZoQLzwSyrrhqXzdPSYfWB52i
    cm.adobe.com/environmentId: "146221"
    cm.adobe.com/programId: "15404"
    cm.adobe.com/tenant: aem-sites-engineering
    environmentId: "146221"
    programId: "15404"
    tenant: aem-sites-engineering
  creationTimestamp: "2023-01-09T10:32:26Z"
  generation: 6
  labels:
    cdn-operator.skyline.adobe.com/transaction-open: "false"
  name: common-p15404-e146221-cm-stg
  namespace: ns-team-aem-cm-stg-n68863
  ownerReferences:
    - apiVersion: skyline.adobe.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: SkylineEnvironmentDomain
      name: cm-p15404-e146221
      uid: 35a5d135-34d5-4a28-9da6-181aed51af3d
  resourceVersion: "1873955529"
  uid: 6814dfb5-bfb7-4f1f-aa0a-9b5fe8291826
spec:
  data:
    dns:
      domains:
        - fqdn: author-p15404-e146221-cmstg.adobeaemcloud.net
          target: ingress.ethos21-stage-nld2.ethos.adobe.net
          type: CNAME
        - fqdn: publish-p15404-e146221-cmstg.adobeaemcloud.net
          target: ingress.ethos21-stage-nld2.ethos.adobe.net
          type: CNAME
        - fqdn: preview-p15404-e146221-cmstg.adobeaemcloud.net
          target: ingress.ethos21-stage-nld2.ethos.adobe.net
          type: CNAME
    service:
      cluster: ethos21-stage-nld2
      cmInstanceName: stg
      domains:
        - name: author-p15404-e146221-cmstg.adobeaemcloud.com
          tier: author
        - name: publish-p15404-e146221-cmstg.adobeaemcloud.com
          tier: publish
        - name: preview-p15404-e146221-cmstg.adobeaemcloud.com
          tier: preview
        - name: static-p15404-e146221-cmstg.adobeaemcloud.com
          tier: static
      environmentId: 146221
      environmentType: dev
      name: common-p15404-e146221-cm-stg
      namespace: ns-team-aem-cm-stg-n68863
      programId: 15404
      toupdate: true
      vcl:
        blueprint: BasicCommon
        blueprint_branch: stage
        blueprint_values:
          author:
            domains:
              - name: author-p15404-e146221-cmstg.adobeaemcloud.com
            skyline_backend_host: author-p15404-e146221-cmstg.adobeaemcloud.net
          azure_container_id: sa0154040shared05ffaebfb
          azure_path_pattern: ^/aem-blob-ns-team-aem-cm-stg-n68863-cm-p15404-e146221.*
          azure_redirect_url_pattern: ^https://(sa0154040shared05ffaebfb.blob.core.windows.net|author-p15404-e146221-cmstg.adobeaemcloud.com)/aem-blob-ns-team-aem-cm-stg-n68863-cm-p15404-e146221.*
          backend_share_key: 891fe089c3b3a264e2419cd38f80abf3
          block_ddos:
            rate_limiter:
              rules:
                - limit: 100
                  name: ip100
                  type: ip
                - limit: 500
                  name: ip500
                  type: ip
                - limit: 100
                  name: tls100
                  type: tls
                - limit: 500
                  name: tls500
                  type: tls
          block_purge:
            key: f9305071a787de4a225340bd6320ae2f9cbf9b01df2bc8fe9d5ce3692ad99a8a
          block_weak_ciphers: true
          byoc: false
          debugHeaders: false
          dm_config:
            backend_host: assets-stage.adobeaemcloud.com
            dm_service_access_key_name: dm_access_key_stg
          enable_blob_private_caching_publish: true
          enable_forms_allowlist_pass: true
          enable_unlocked_byocdn: true
          forceTls: true
          forceVersion: 1673892425
          health_check_url: /systemready
          messageVersion: e4dfdd424567977a49d12b1c995d584a
          preview:
            domains:
              - name: preview-p15404-e146221-cmstg.adobeaemcloud.com
            skyline_backend_host: preview-p15404-e146221-cmstg.adobeaemcloud.net
            whitelist_ip:
              - cidr:
                  - ip: 0.0.0.0
                    mask: 32
                name: generated
                url: /
          publish:
            domains:
              - name: publish-p15404-e146221-cmstg.adobeaemcloud.com
            skyline_backend_host: publish-p15404-e146221-cmstg.adobeaemcloud.net
          sky_edge_key1: e7f-130f3bbeb7fea0cd55e53c003253f3b7b883bb945c09b9919146795f8f0cbbc8
          static:
            domains:
              - name: static-p15404-e146221-cmstg.adobeaemcloud.com
          use_explicit_assets_content_disposition: true
          x-edge-key: 10211d2885196b97b1c78e1672f3f68ae97c294596ef2b7fd890cbd30a3427bf
    state:
      dns:
        domains:
          - changeId: /change/C00985072FEJ6N0Q8VMOP
            fqdn: author-p15404-e146221-cmstg.adobeaemcloud.net
            sha1: 0b21710c99141cd969491af05be4b24bc8dad1b4
            submittedAt: "2023-01-09T10:32:28.410Z"
            target: ingress.ethos21-stage-nld2.ethos.adobe.net
            type: CNAME
            zoneid: Z1H6OV713OOQRA
          - changeId: /change/C00985072FEJ6N0Q8VMOP
            fqdn: publish-p15404-e146221-cmstg.adobeaemcloud.net
            sha1: 0b21710c99141cd969491af05be4b24bc8dad1b4
            submittedAt: "2023-01-09T10:32:28.410Z"
            target: ingress.ethos21-stage-nld2.ethos.adobe.net
            type: CNAME
            zoneid: Z1H6OV713OOQRA
          - changeId: /change/C00985072FEJ6N0Q8VMOP
            fqdn: preview-p15404-e146221-cmstg.adobeaemcloud.net
            sha1: 0b21710c99141cd969491af05be4b24bc8dad1b4
            submittedAt: "2023-01-09T10:32:28.410Z"
            target: ingress.ethos21-stage-nld2.ethos.adobe.net
            type: CNAME
            zoneid: Z1H6OV713OOQRA
      service:
        currentversion: 3
        domains:
          - fastly_created_at: "2023-01-09T10:32:29Z"
            name: author-p15404-e146221-cmstg.adobeaemcloud.com
          - fastly_created_at: "2023-01-09T10:32:31Z"
            name: publish-p15404-e146221-cmstg.adobeaemcloud.com
          - fastly_created_at: "2023-01-09T10:32:33Z"
            name: preview-p15404-e146221-cmstg.adobeaemcloud.com
          - fastly_created_at: "2023-01-09T10:32:35Z"
            name: static-p15404-e146221-cmstg.adobeaemcloud.com
        fastlyid: t7yn3zOjPad71MvXVcS212
        logging:
          splunk:
            created_at: "2023-01-09T10:32:37Z"
            sha1: 55252c39b15aab13f53ebe5d4d791a046d033765
            updated_at: "2023-01-16T18:07:08Z"
        vcl:
          blueprintInfo: stage|fd0406a848799919e197556f03ae7b6fa4046fd7
          sha1: f0cc5506cdf9dafa5eda50a7cda209450de55090
      sha1: ec1a79becd704eb69c83b4cca3131c65d9ad8fca
    tls: {}
  retries: 5
status:
  observedGeneration: 6
  retryCount: 0
  state: applied
